version: "3"

services:
  mysql:
    image: loosemond:mysql_server
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
  web_python:
    build: ./volumes/python/
    ports:
      - "5000:5000"
    volumes:
      - "./volumes/python:/usr/src/app"
    depends_on:
      - mysql
